spring.application.name=EcommerceBackend
server.port=9090

#postgre sql setup
spring.datasource.url=jdbc:postgresql://localhost:5432/divyanshu
spring.datasource.username=postgres
spring.datasource.password=9211
spring.datasource.driver-class-name=org.postgresql.Driver

#create tables automatically if exits update or create a new table
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Cloudinary setup
cloudinary.cloud-name=dycnvpf6q
cloudinary.api-key=266798281974722
cloudinary.api-secret=WMhL8u8VWgtmYGykspf-3bEl_rc
cloudinary.upload-preset=ecommerce_unsigned

#multer for file uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.servlet.session.cookie.same-site=STRICT

jwt.secret=8nIfBUrISuiI8lg7SMDJkh6ozQt3YgFtNkZh7WpMOesipOUlQo
jwt.expiration=10800000

# logging.level.org.springframework=DEBUG